ctibutler/server/arango_helpers.py

alias now searches doc.`aliases` too 

---

ctibutler/server/arango_helpers.py
ctibutler/server/views.py

add "object/<ext_id>/bundle" paths

---

ctibutler/server/arango_helpers.py
ctibutler/server/views.py

implement `attack_type, disarm_type, atlas_type` filters

---

ctibutler/server/views.py

add truncate endpoints #79

---

ctibutler/server/arango_helpers.py
ctibutler/server/serializers.py
ctibutler/server/views.py

add location_id filter

---

ctibutler/server/arango_helpers.py
ctibutler/server/views.py

Retrieve object now returns only the object with latest version in _stix2arango_note

---

ctibutler/server/arango_helpers.py
ctibutler/server/views.py

add support for stix_id in `$VIEW/objects/<object_id>/*`

---

ctibutler/server/arango_helpers.py

always use latest version filter instead of _is_latest #100

---

ctibutler/server/arango_helpers.py

Fix bundle rels inconsistency

---

ctibutler/server/arango_helpers.py

fix regression causing version filter to always return nothing

---

ctibutler/worker/tasks.py

auto remove tempdir for job if job fails

---

.github/workflows/schemathesis.yml
requirements.txt
tests/test_08_objects.py

test objects path

---

ctibutler/server/arango_helpers.py
ctibutler/server/views.py

add types filter to bundle endpoints

---

tests/test_01_upload_bundles.py
tests/test_03_generic_paths.py

fix test issues from stale ATLAS import

---

utilities/import_all_data.py

add `all` version; validate version before start

---

.github/workflows/run-tests.yml
ctibutler/server/serializers.py
ctibutler/server/views.py
ctibutler/worker/tasks.py
tests/full/test_10_truncate.py
tests/st/test_schemathesis.py
utilities/import_all_data.py

fix schemathesis test

---

ctibutler/server/arango_helpers.py
ctibutler/server/views.py
tests/full/test_09_semantic_search.py

implement `include_revoked` and `include_deprecated` on `/search/`

---

ctibutler/server/arango_helpers.py
ctibutler/server/views.py

closes  #194 #195 #197 #198 #199

add type and *_id sorts to all endpoints

---

ctibutler/server/serializers.py
ctibutler/server/views.py
tests/full/test_19_truncate.py

fix navigator schema; make truncate sync

---

ctibutler/server/arango_helpers.py
ctibutler/server/views.py
tests/full/test_04_filters_generic.py

bring name filter back
